version: 1.0.{build}
image:
  - Visual Studio 2017
  - Ubuntu1804
environment:
  nodejs_version: "10"
build_script:
  - sh: >-
      yarn
      yarn build-release
  - cmd: >-
      yarn
      yarn build-release
artifacts:
  - path: dist/**
    name: forward-logs
deploy:
  - provider: GitHub
    auth_token:
      secure: JQfHIn6VDr0Lw+NhQ51C7Jjd1vK7fW4vuT6iMlf40Ni07AbP4zhEylS1JTxTWIPP
    artifact: forward-logs
