version: 1.0.{build}
skip_tags: true
image:
  - Visual Studio 2017
  - Ubuntu1804
stack: node 10
install:
  - cmd: powershell Install-Product node 10
build_script:
  - yarn
  - yarn gulp release
artifacts:
  - path: dist/**
    name: forward-logs
deploy:
  - provider: GitHub
    auth_token:
      secure: JQfHIn6VDr0Lw+NhQ51C7Jjd1vK7fW4vuT6iMlf40Ni07AbP4zhEylS1JTxTWIPP
    artifact: forward-logs
    on:
      branch: master
